config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registritions: 'users/registrations'
  }
  resources :users, only: [:show]
  get 'diagnoses/new'
  get 'diagnoses/index'
  resources :power_stones, shallow: true do
    collection do
      get :have_stones
    end
    collection do
      get :want_stones
    end
  end
  resources :have_stones, only: %i[create destroy]
  resources :want_stones, only: %i[create destroy]
  root 'tops#index'
  get 'posts/index'
  resources :users do
    get 'want_stones', on: :member
    get 'have_stones', on: :member
  end
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :email, confirmation: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :stone_categories, dependent: :destroy
  has_many :power_stones, through: :stone_categories, dependent: :destroy
end

app/models/have_stone.rb
class HaveStone < ApplicationRecord
  belongs_to :user
  belongs_to :power_stone, class_name: "PowerStone"
  validates :user_id, uniqueness: { scope: :power_stone_id}
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :picture_id, PowerStoneImageUploader
    belongs_to :user

    validates :title, presence: true, length: { maximum: 255 }
    validates :content, presence: true, length: { maximum: 10_535 }
end

app/models/power_stone.rb
class PowerStone < ApplicationRecord
  mount_uploader :power_stone_image, PowerStoneImageUploader
  has_many :stone_categories, dependent: :destroy
  has_many :categories, through: :stone_categories, dependent: :destroy
  has_many :have_stones, dependent: :destroy
  has_many :have_stone_power_stones, dependent: :destroy, class_name: "HaveStone"
  has_many :have_stone_users, through: :have_stone_power_stones, source: :user
  has_many :want_stones, dependent: :destroy
  has_many :want_stone_power_stones, dependent: :destroy, class_name: "HaveStone"
  has_many :want_stone_users, through: :want_stone_power_stones, source: :user
  validates :name, presence: true, length: { maximum: 20}
  validates :overview, presence: true, length: { maximum: 10_535 }
end

app/models/stone_category.rb
class StoneCategory < ApplicationRecord
  belongs_to :power_stone
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*[a-z])(?=.*\d)[a-z\d]{8,}+\z/
  validates :name, presence: true, length: { in: 1..10 }
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX, message: "を○○@○○.○○の形式で入力して下さい" }, length: { maximum: 255 }
  validates :password, presence: true, length: { maximum: 75 }, format: { with: VALID_PASSWORD_REGEX, message: "を半角英数字8文字以上で入力して下さい" }
  validates :email, confirmation: true
  has_many :have_stones, dependent: :destroy
  has_many :have_stone_power_stones, through: :have_stones, source: :power_stone
  has_many :want_stones, dependent: :destroy
  has_many :want_stone_power_stones, through: :want_stones, source: :power_stone
  has_many :posts, dependent: :destroy
  
  def have_stone(power_stone)
    have_stone_power_stones << power_stone
  end

  def unhave_stone(power_stone)
    have_stone_power_stones.destroy(power_stone)
  end

  def have_stone?(power_stone)
    have_stone_power_stones.include?(power_stone)
  end

  def want_stone(power_stone)
    want_stone_power_stones << power_stone
  end

  def unwant_stone(power_stone)
    want_stone_power_stones.destroy(power_stone)
  end

  def want_stone?(power_stone)
    want_stone_power_stones.include?(power_stone)
  end

end

app/models/want_stone.rb
class WantStone < ApplicationRecord
  belongs_to :user
  belongs_to :power_stone
  validates :user_id, uniqueness: { scope: :power_stone_id}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ edit update destroy]
  before_action :authenticate_user!, only: %i[ edit update destroy new show index]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to posts_path, notice: '投稿しました'
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "更新しました" 
    else
      flash.now[:alert] = '更新に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: '削除しました'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :picture_id, :picture_id_cache)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = "StoneMatching" #これがサイトのブランド名
    title = @page_title + " | " + title if @page_title
    title
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "warning"
    when "notice"
      "success"
    when "error"
      "danger"
    end
  end
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/have_stones_helper.rb
module HaveStonesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/power_stones_helper.rb
module PowerStonesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/want_stones_helper.rb
module WantStonesHelper
end

app/views/admins/index.html.erb
    <section class="min-h-96 flex justify-center items-center flex-1 shrink-0 bg-gray-100 overflow-hidden shadow-lg rounded-lg relative py-16 md:py-20 xl:py-48">
      <!-- image - start -->
      <!--img src="assets/images/25010926_s.jpg" alt="Photo by Fakurian Design" class="w-full h-full object-cover object-center absolute inset-0"-->
      <!-- image - end -->
      <!-- overlay - start -->
      <%= image_tag "top.jpg",alt: "トップ画像", class: "w-full h-full object-cover object-center absolute inset-0" %>
      <!-- overlay - end -->

      <!-- text start -->
      <div class="sm:max-w-xl flex flex-col items-center relative p-4">
        <p class="text-red-700 text-lg sm:text-xl text-center mb-4 md:mb-8">パワーストーン診断アプリ</p>
        <h1 class="text-blue-700 text-4xl sm:text-5xl md:text-6xl font-bold text-center mb-8 md:mb-12">StoneMatching</h1>

        <div class="w-full flex flex-col sm:flex-row sm:justify-center gap-2.5">
        <%= link_to "診断する", diagnoses_new_path, class: "inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3" %>

      <!-- text end -->
    </section>
<!-- hero - end -->

app/views/admins/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
        count: resource.errors.count,
        resource: resource.class.model_name.human.downcase)
  ul
    - resource.errors.full_messages.each do |message|
      li
        = message

app/views/admins/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "ログイン", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "ユーザー（管理者）登録", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "パスワードをお忘れですか?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post
    br

app/views/layouts/application.html.slim
doctype html
html
  head
  body
    = render 'shared/header'
    - if notice.present?
      .flex.items-center.justify-center.h-screen
        p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
          = notice
    - if alert.present?
      .flex.items-center.justify-center.h-screen
        p#alert.py-2.px-3.bg-red-50.mb-5.text-red-500.font-medium.rounded-lg.inline-block
          = alert
    = yield
    = render 'shared/footer'

app/views/shared/_error_message.html.slim
- if post.errors.any?
  div#error_messages.alert.alert-danger
    ul.mb-0
      - post.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_message.html.slim
- flash.each do |message_type, message|
    = content_tag :div, message, class: message_type

app/views/shared/_footer.html.slim
footer#footer.footer-bottom
  .container
    .row
      .col-sm-6.col-12
        .copyright
          p 2023. StoneMatching

app/views/shared/_header.html.slim
  head
    title
      | StoneMatching
      meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "application", "inter-font", "data-turbo-track": "reload" 
    = javascript_importmap_tags
    .pb-6.sm:pb-8.lg:pb-12
      .max-w-screen-2xl.px-4.md:px-8.mx-auto
        header.flex.justify-between.items-center.py-4.md:py-8.mb-4
          a.inline-flex.items-center.text-blue-700.text-2xl.md:text-3xl.font-bold.gap-2.5[href="/" aria-label="logo"]
            =image_tag "kouseki_colorful.png",size: "30x30"
              path[d="M96 0V47L48 94H0V47L48 0H96Z"]
            |  StoneMatching
            =image_tag "kouseki_colorful.png",size: "30x30"
          .font-bold.py-2.px-4
          - if user_signed_in?
            = link_to '投稿一覧へ', posts_path, class: "inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3"
            = link_to '新規投稿へ', new_post_path, style: "background-color: orange; color: white;", class: "rounded-lg py-3 px-5 inline-block font-medium"
            = link_to 'パワーストーン一覧へ', power_stones_path, style: "background-color: green; color: white;", class: "rounded-lg py-3 px-5 inline-block font-medium"
            = link_to 'マイページ', user_path(current_user), style: "background-color: blue; color: white;", class: "rounded-lg py-3 px-5 inline-block font-medium"
            = link_to 'ログアウト', destroy_user_session_path, style: "background-color: red; color: white;", class: "rounded-lg py-3 px-5 inline-block font-medium"
          - elsif admin_signed_in?
            = link_to '投稿一覧へ', posts_pathclass: "inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3"
            = link_to 'パワーストーン一覧へ', power_stones_path, style: "background-color: green; color: white;", class: "rounded-lg py-3 px-5 inline-block font-medium"
            = link_to 'パワーストーン新規登録', new_power_stone_path
            = link_to 'ログアウト', destroy_admin_session_path, style: "background-color: red; color: white;", class: "rounded-lg py-3 px-5 inline-block font-medium"
          - else
            =link_to 'ユーザー登録', new_user_registration_path,  style: "background-color: green; color: white;", class: "rounded-lg py-3 px-5 inline-block font-medium"
            =link_to 'ログイン', new_user_session_path,  style: "background-color: blue; color: white;", class: "rounded-lg py-3 px-5 inline-block font-medium"
        