config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registritions: 'users/registrations'
  }
  resources :users, only: [:show]
  get 'diagnoses/new'
  get 'diagnoses/index'
  resources :power_stones, shallow: true do
    collection do
      get :have_stones
    end
    collection do
      get :want_stones
    end
  end
  resources :have_stones, only: %i[create destroy]
  resources :want_stones, only: %i[create destroy]
  root 'tops#index'
  get 'posts/index'
  resources :users do
    get 'want_stones', on: :member
    get 'have_stones', on: :member
  end
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*[a-z])(?=.*\d)[a-z\d]{8,}+\z/
  validates :name, presence: true, length: { in: 1..10 }
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX, message: "を○○@○○.○○の形式で入力して下さい" }, length: { maximum: 255 }
  validates :password, presence: true, length: { maximum: 75 }, format: { with: VALID_PASSWORD_REGEX, message: "を半角英数字8文字以上で入力して下さい" }
  validates :email, confirmation: true
  has_many :have_stones, dependent: :destroy
  has_many :have_stone_power_stones, through: :have_stones, source: :power_stone
  has_many :want_stones, dependent: :destroy
  has_many :want_stone_power_stones, through: :want_stones, source: :power_stone
  has_many :posts, dependent: :destroy
  
  def have_stone(power_stone)
    have_stone_power_stones << power_stone
  end

  def unhave_stone(power_stone)
    have_stone_power_stones.destroy(power_stone)
  end

  def have_stone?(power_stone)
    have_stone_power_stones.include?(power_stone)
  end

  def want_stone(power_stone)
    want_stone_power_stones << power_stone
  end

  def unwant_stone(power_stone)
    want_stone_power_stones.destroy(power_stone)
  end

  def want_stone?(power_stone)
    want_stone_power_stones.include?(power_stone)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @power_stones = @user.have_stone_power_stones
  end

  def index
  end

  def want_stones
    @user = User.find(params[:id])
    @want_stones = @user.want_stones
  end

  def have_stones
    @user = User.find(params[:id])
    @have_stones = @user.have_stones
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_post.html.slim
.w-full
p.my-5
  strong.block.font-medium.mb-1
    | 投稿者:
  = post.user.name
p.my-5
  strong.block.font-medium.mb-1
    | タイトル:
  = post.title
p.my-5
  strong.block.font-medium.mb-1
    | 記事:
  = post.content
p.my-5
  strong.block.font-medium.mb-1
  = image_tag post.picture_id.url, id: 'preview', size: '200x200'
p.small
  strong.block.font-medium.mb-1
    | 投稿日時:
  = post.created_at
- if action_name != "show"
  = link_to "投稿詳細へ", post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to '投稿編集へ', edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
  hr.mt-6

app/views/users/have_stone_list.html.slim
h1 Power Stones Owned by #{@user.name}

- @power_stones.each do |power_stone|
  = power_stone.name
  = power_stone.overview

app/views/users/have_stones.html.slim
.mx-auto.md:w-2/3.w-full    
  h1.font-bold.text-4xl
    | 所持リスト登録済み一覧
  - @have_stones.each do |have_stone|
    p.my-5
      strong.block.font-medium.mb-1
        | 名前:
      = have_stone.power_stone.name
    p.my-5
      strong.block.font-medium.mb-1
        | 説明:
    = have_stone.power_stone.overview
    = image_tag have_stone.power_stone.power_stone_image.url, id: 'preview', size: '200x200'
    /= render 'power_stones/have_stone_area', power_stone: power_stone
    /= render 'power_stones/want_stone_area', power_stone: power_stone

app/views/users/show.html.slim
.mx-auto.md:w-2/3.w-full
  h1.text-2xl
    = @user.name
    | さんのマイページ
  .my5
  = link_to '欲しい石登録済みリスト', want_stones_user_path(@user), style: "background-color: purple; color: white;", class: "rounded-lg py-3 ml-2 px-5 inline-block font-medium"
  .my-5 
  = link_to '所持リスト登録済みリストへ', have_stones_user_path(@user),style: "background-color: pink; color: white;",  class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
  h1.text-xl
    | 過去の投稿
  p
  - @user.posts.each do |post|
    p.my-5
      strong.block.font-medium.mb-1
        |タイトル:
        = post.title 
        | 
    p.my-5
      strong.block.font-medium.mb-1
        |記事:
        = post.content 
    p.my-5
      strong.block.font-medium.mb-1
        |画像:
      = image_tag post.picture_id.url, id: 'preview', size: '200x200'
    p
      = link_to "投稿詳細へ", post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
      = link_to '投稿編集へ', edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    hr.mt-6
  p.my5


  hr.mt-6

app/views/users/want_stones.html.slim
.mx-auto.md:w-2/3.w-full    
  h1.font-bold.text-4xl
    | 欲しい石リスト登録済み一覧
  - @want_stones.each do |want_stone|
    p.my-5
      strong.block.font-medium.mb-1
        | 名前:
      = want_stone.power_stone.name
    p.my-5
      strong.block.font-medium.mb-1
        | 説明:
    = want_stone.power_stone.overview
    = image_tag want_stone.power_stone.power_stone_image.url, id: 'preview', size: '200x200'