config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registritions: 'users/registrations'
  }
  resources :users, only: [:show]
  get 'diagnoses/new'
  get 'diagnoses/index'
  resources :power_stones, shallow: true do
    collection do
      get :have_stones
    end
    collection do
      get :want_stones
    end
  end
  resources :have_stones, only: %i[create destroy]
  resources :want_stones, only: %i[create destroy]
  root 'tops#index'
  get 'posts/index'
  resources :users do
    get 'want_stones', on: :member
    get 'have_stones', on: :member
  end
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :email, confirmation: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :stone_categories, dependent: :destroy
  has_many :power_stones, through: :stone_categories, dependent: :destroy
end

app/models/have_stone.rb
class HaveStone < ApplicationRecord
  belongs_to :user
  belongs_to :power_stone, class_name: "PowerStone"
  validates :user_id, uniqueness: { scope: :power_stone_id}
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :picture_id, PowerStoneImageUploader
    belongs_to :user

    validates :title, presence: true, length: { maximum: 255 }
    validates :content, presence: true, length: { maximum: 10_535 }
end

app/models/power_stone.rb
class PowerStone < ApplicationRecord
  mount_uploader :power_stone_image, PowerStoneImageUploader
  has_many :stone_categories, dependent: :destroy
  has_many :categories, through: :stone_categories, dependent: :destroy
  has_many :have_stones, dependent: :destroy
  has_many :have_stone_power_stones, dependent: :destroy, class_name: "HaveStone"
  has_many :have_stone_users, through: :have_stone_power_stones, source: :user
  has_many :want_stones, dependent: :destroy
  has_many :want_stone_power_stones, dependent: :destroy, class_name: "HaveStone"
  has_many :want_stone_users, through: :want_stone_power_stones, source: :user
  validates :name, presence: true, length: { maximum: 20}
  validates :overview, presence: true, length: { maximum: 10_535 }
end

app/models/stone_category.rb
class StoneCategory < ApplicationRecord
  belongs_to :power_stone
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*[a-z])(?=.*\d)[a-z\d]{8,}+\z/
  validates :name, presence: true, length: { in: 1..10 }
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX, message: "を○○@○○.○○の形式で入力して下さい" }, length: { maximum: 255 }
  validates :password, presence: true, length: { maximum: 75 }, format: { with: VALID_PASSWORD_REGEX, message: "を半角英数字8文字以上で入力して下さい" }
  validates :email, confirmation: true
  has_many :have_stones, dependent: :destroy
  has_many :have_stone_power_stones, through: :have_stones, source: :power_stone
  has_many :want_stones, dependent: :destroy
  has_many :want_stone_power_stones, through: :want_stones, source: :power_stone
  has_many :posts, dependent: :destroy
  
  def have_stone(power_stone)
    have_stone_power_stones << power_stone
  end

  def unhave_stone(power_stone)
    have_stone_power_stones.destroy(power_stone)
  end

  def have_stone?(power_stone)
    have_stone_power_stones.include?(power_stone)
  end

  def want_stone(power_stone)
    want_stone_power_stones << power_stone
  end

  def unwant_stone(power_stone)
    want_stone_power_stones.destroy(power_stone)
  end

  def want_stone?(power_stone)
    want_stone_power_stones.include?(power_stone)
  end

end

app/models/want_stone.rb
class WantStone < ApplicationRecord
  belongs_to :user
  belongs_to :power_stone
  validates :user_id, uniqueness: { scope: :power_stone_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
  end
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
before_action :set_power_stone, only: %i[ index ]
before_action :set_checkdata, only: %i[ index ]
  def index
    if @selected_category_ids == nil
      redirect_to diagnoses_new_path, alert: '「 1つ以上チェックが必要です 」'
    else
      @power_stones.each do |power_stone|
        tmp_match_category_count = 0
        power_stone.categories.each do |category|
          if @selected_category_ids&.include?(category.id.to_s)
            tmp_match_category_count = tmp_match_category_count + 1 
          end
        end

        if @match_category_count < tmp_match_category_count
           @matched_power_stones = []
           @matched_power_stones << power_stone
           @match_category_count = tmp_match_category_count
        elsif @match_category_count == tmp_match_category_count
           @matched_power_stones << power_stone
        end
      end
    end
  end

  private
    def set_power_stone
      @power_stones = PowerStone.all
    end

    def set_checkdata
      @selected_category_ids = params[:answer]
      @match_category_count = 0
      @tmp_match_category_count = 0
      @matched_power_stones = []
    end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ edit update destroy]
  before_action :authenticate_user!, only: %i[ edit update destroy new show index]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to posts_path, notice: '投稿しました'
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "更新しました" 
    else
      flash.now[:alert] = '更新に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: '削除しました'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :picture_id, :picture_id_cache)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @power_stones = @user.have_stone_power_stones
  end

  def index
  end

  def want_stones
    @user = User.find(params[:id])
    @want_stones = @user.want_stones
  end

  def have_stones
    @user = User.find(params[:id])
    @have_stones = @user.have_stones
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = "StoneMatching" #これがサイトのブランド名
    title = @page_title + " | " + title if @page_title
    title
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "warning"
    when "notice"
      "success"
    when "error"
      "danger"
    end
  end
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/have_stones_helper.rb
module HaveStonesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/power_stones_helper.rb
module PowerStonesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/want_stones_helper.rb
module WantStonesHelper
end

app/views/posts/_form.html.slim
= form_with(model: post, class: "contents") do |form|
  - if post.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      h2
        = pluralize(post.errors.count, "件のエラー")
        |  この投稿は保存されませんでした
    ul
      - post.errors.each do |error|
        li
          = error.full_message
  .my-5
    = form.label :"title"
    = form.text_field :"title", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :"content"
    = form.text_area :"content", rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  div class="form-group"
    = form.label :"picture_id"
    = form.file_field :"picture_id", class: 'form-control mb-3', accept: 'image/*'
    = form.hidden_field :picture_id_cache
    = image_tag post.picture_id.url, id: 'preview', size: '200x200'
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/posts/_post.html.slim
.w-full
p.my-5
  strong.block.font-medium.mb-1
    | 投稿者:
  = post.user.name
p.my-5
  strong.block.font-medium.mb-1
    | タイトル:
  = post.title
p.my-5
  strong.block.font-medium.mb-1
    | 記事:
  = post.content
  = image_tag post.picture_id.url, id: 'preview', size: '200x200'
p.small
  strong.block.font-medium.mb-1
    | 投稿日時:
  = post.created_at
- if action_name != "show"
  = link_to "投稿詳細へ", post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
- if admin_signed_in?
  = link_to '投稿編集へ', edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
- elsif current_user.id == post.user.id 
  = link_to '投稿編集へ', edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
  hr.mt-6

app/views/posts/edit.html.slim
.mx-auto.md:w-2/3.w-full
  h1.font-bold.text-4xl
    | 投稿編集
  = render "form", post: @post
  = button_to '削除', post_path(@post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
  = link_to "投稿詳細へ", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "投稿一覧へ", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/posts/index.html.slim
 .mx-auto.md:w-2/3.w-full    
  h1.font-bold.text-4xl
    | 投稿一覧
  tr
    th= render @posts

app/views/posts/new.html.slim
.mx-auto.md:w-2/3.w-full
  h1.font-bold.text-4xl
    | 新規投稿
  = render "form", post: @post
  = link_to '投稿一覧へ', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/posts/show.html.slim
mx-auto.md:w-2/3.w-full.flex
  .mx-auto
    - if notice.present?
      p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
        = notice
    = render @post
    /= link_to '投稿編集', edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    /.inline-block.ml-2
    /= button_to '削除', post_path(@post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to '投稿一覧へ', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"