config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registritions: 'users/registrations'
  }
  resources :users, only: [:show]
  get 'diagnoses/new'
  get 'diagnoses/index'
  resources :power_stones, shallow: true do
    collection do
      get :have_stones
    end
    collection do
      get :want_stones
    end
  end
  resources :have_stones, only: %i[create destroy]
  resources :want_stones, only: %i[create destroy]
  root 'tops#index'
  get 'posts/index'
  resources :users do
    get 'want_stones', on: :member
    get 'have_stones', on: :member
  end
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/power_stone.rb
class PowerStone < ApplicationRecord
  mount_uploader :power_stone_image, PowerStoneImageUploader
  has_many :stone_categories, dependent: :destroy
  has_many :categories, through: :stone_categories, dependent: :destroy
  has_many :have_stones, dependent: :destroy
  has_many :have_stone_power_stones, dependent: :destroy, class_name: "HaveStone"
  has_many :have_stone_users, through: :have_stone_power_stones, source: :user
  has_many :want_stones, dependent: :destroy
  has_many :want_stone_power_stones, dependent: :destroy, class_name: "HaveStone"
  has_many :want_stone_users, through: :want_stone_power_stones, source: :user
  validates :name, presence: true, length: { maximum: 20}
  validates :overview, presence: true, length: { maximum: 10_535 }
end

app/controllers/power_stones_controller.rb
class PowerStonesController < ApplicationController
  before_action :set_power_stone, only: %i[ edit update destroy show have_stones want_stones]
  before_action :move_to_root, only: %i[ new update destroy edit] 
  before_action :authenticate_admin!, only: %i[ new update destroy edit ] 
  # GET /power_stones or /power_stones.json
  def index
    #@power_stones = PowerStone.all
    @power_stones = PowerStone.all.includes([:have_stones])
  end

  # GET /power_stones/1 or /power_stones/1.json
  def show
  end

  # GET /power_stones/new
  def new
    @power_stone = PowerStone.new
  end

  # GET /power_stones/1/edit
  def edit
  end

  # POST /power_stones or /power_stones.json
  def create
    @power_stone = PowerStone.new(power_stone_params)
    if @power_stone.save
      redirect_to power_stone_url(@power_stone), notice: "Power stone was successfully created." 
    else
      render :new, status: :unprocessable_entity
    end
    
  end

  # PATCH/PUT /power_stones/1 or /power_stones/1.json
  def update
    if @power_stone.update(power_stone_params)
      redirect_to power_stone_url(@power_stone), notice: "Power stone was successfully updated." 
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /power_stones/1 or /power_stones/1.json
  def destroy
    @power_stone.destroy
    redirect_to power_stones_url, notice: "Power stone was successfully destroyed." 
  end

  def have_stones
    @have_stone_power_stones = current_user.have_stone_power_stones.includes(:user).order(created_at: :desc)
  end

  def want_stones
    @want_stone_power_stones = current_user.want_stone_power_stones.includes(:user).order(created_at: :desc)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_power_stone
      @power_stone = PowerStone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def power_stone_params
      params.require(:power_stone).permit(:name, :overview, :power_stone_image,  :power_stone_image_cache, category_ids: [])
    end

    def move_to_root
      unless admin_signed_in?
        redirect_to root_path
      end
    end
end

app/helpers/power_stones_helper.rb
module PowerStonesHelper
end

app/views/power_stones/_form.html.slim
= form_with(model: power_stone, class: "contents") do |form|
  - if power_stone.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      h2
        = pluralize(power_stone.errors.count, "error")
        |  prohibited this power_stone from being saved:
    ul
      - power_stone.errors.each do |error|
        li
          = error.full_message
  .my-5
    = form.label :name
    = form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :overview
    = form.text_area :overview, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  div class="form-group"
    = form.label :power_stone_image
    = form.file_field :power_stone_image, class: 'form-control mb-3', accept: 'image/*'
    = form.hidden_field :power_stone_image_cache
    = image_tag power_stone.power_stone_image.url, id: 'preview', size: '200x200'
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"
  .form-group
    = form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category|
      .form-check
        = category.label class: 'form-check-label' do
          = category.check_box class: 'form-check-input'
          = category.text

app/views/power_stones/_have_stone_area.html.slim
- if current_user.have_stone?(power_stone)
  = link_to "所持リストから削除", have_stone_path(current_user.have_stones.find_by(power_stone_id: power_stone.id)), data: { turbo_method: :delete }, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
- else
  = link_to "所持リストへ追加", have_stones_path(power_stone_id: power_stone.id), data: { turbo_method: :post }, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"

app/views/power_stones/_power_stone.html.slim
 <div id="= dom_id power_stone "> 
  p.my-5
    strong.block.font-medium.mb-1
      | 名前:
    = power_stone.name
  p.my-5
    strong.block.font-medium.mb-1
      | 説明:
    = power_stone.overview
    = image_tag power_stone.power_stone_image.url, id: 'preview', size: '200x200'
  /- if action_name != "show"
  - if admin_signed_in?
    = link_to "パワーストーン詳細", power_stone, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to "パワーストーン編集", edit_power_stone_path(power_stone), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    hr.mt-6
  - elsif user_signed_in?
    = render 'have_stone_area', power_stone: power_stone
    = render 'want_stone_area', power_stone: power_stone
  hr.mt-6

app/views/power_stones/_want_stone_area.html.slim
- if current_user.want_stone?(power_stone)
  = link_to "欲しい石リストから削除", want_stone_path(current_user.want_stones.find_by(power_stone_id: power_stone.id)), data: { turbo_method: :delete }, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
- else
  = link_to "欲しい石リストへ追加", want_stones_path(power_stone_id: power_stone.id), data: { turbo_method: :post }, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"

app/views/power_stones/edit.html.slim
.mx-auto.md:w-2/3.w-full
  h1.font-bold.text-4xl
    | Editing power stone
  = render "form", power_stone: @power_stone
  = link_to "Show this power stone", @power_stone, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to power stones", power_stones_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/power_stones/have_stones.html.slim
.container.pt-3
  | 掲示板一覧
  .row
    .col-12
      .row

      powe_stone = @user.have_stones.select(:have_stone_id)
        /- if @have_stone_power_stones.present?
          = render @have_stone_power_stones
        /- else
          p= t('.no_result')
          @have_stone_power_stones

app/views/power_stones/index.html.slim
 .mx-auto.md:w-2/3.w-full
  .flex.justify-between.items-center
    h1.font-bold.text-4xl
      | パワーストーン一覧
  #power_stones.min-w-full
    = render @power_stones

app/views/power_stones/new.html.slim
.mx-auto.md:w-2/3.w-full
  h1.font-bold.text-4xl
    | パワーストーン 新規作成
  = render "form", power_stone: @power_stone
  = link_to 'パワーストーン一覧へ', power_stones_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/power_stones/show.html.slim
.mx-auto.md:w-2/3.w-full.flex
  .mx-auto
    - if notice.present?
      p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
        = notice
    = render @power_stone
    = link_to 'Edit this power_stone', edit_power_stone_path(@power_stone), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    .inline-block.ml-2
      = button_to 'Destroy this power_stone', power_stone_path(@power_stone), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to 'Back to power_stones', power_stones_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/power_stones/want_stones.html.slim
- content_for(:title, t('.title'))
.container.pt-3
  .row
    .col-lg-10.offset-lg-1
      form
        .input-group.mb-3
          input.form-control[placeholder="検索ワード" type="search"]
          .input-group-append
            input.btn.btn-primary[type="submit" value="検索"]
  .row
    .col-12
      .row
        - if @want_stone_power_stones.present?
          = render partial: "power_stone", collection: @want_stone_power_stones
        - else
          p
            | ブックマーク中の掲示板がありません